---

- hosts: localhost
  roles:
  - { role: desktop, tags: desktop }
  - { role: ext, tags: ext }
  - { role: bashrc, tags: bashrc }
  - { role: dotfiles, tags: dotfiles }
  # depends on the desktop (personal, professional, ...)
  - { role: custom, tags: custom }
