---

- name: create ~/opt and ~/.local/bin directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/opt/
    - ~/.local/bin/

- include_tasks: managed_ubuntu.yml
  when: ansible_domain | regex_search(".int.")

- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"
